FROM node:12.11.0
MAINTAINER tech@texastribune.org

RUN mkdir /app
WORKDIR /app

COPY package.json /app/
COPY yarn.lock /app/
RUN yarn

COPY . /app/

RUN yarn run dash:test:webpack

ENTRYPOINT ["/app/docker-test-entrypoint.sh"]
