# example of a production Makefile

NS:=namespace
APP:=dot
BRANCH:=master

app: free-space
	git fetch && \
	git reset --hard origin/${BRANCH}
	docker build -t ${NS}/${APP} .
	-docker rm -f ${APP}
	docker run --detach \
		--publish=3000:3000 \
		--restart=always \
		--name=${APP} \
		--hostname=$$(hostname) \
		--env-file=env ${NS}/${APP}

free-space:
	docker system prune -f

logs:
	docker logs --follow ${APP}
