name: Publish to Dockerhub

# publish the image for PRs or pushes to master or on releases
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published, created, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: texastribune/dot
          cache_froms: texastribune/dot:latest
          add_git_labels: true # adds some helpful metadata according to opencontainers image spec
          tag_with_ref: true